version: '3.5'

services:
  postgresql:
    build: .
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#      PGPASSFILE: '/.pgpass'
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    networks:
      - novesfora-net

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - 80:80
    links:
      - postgresql
    networks:
      - novesfora-net


networks:
  novesfora-net:
    external:
      name: novesfora_network
